[package]
name = "sheeshwow/component"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Contribution to sleitnick's component. Added some methods and GUID catching. Added pointers"

[dependencies]
Promise = "kineticwallet/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
Janitor = "kineticwallet/janitor@1.15.7"
Fusion = "elttob/fusion@0.3.0"

